Repository szollingerrajmund/SpaceHunter, pull requests merged in 2024-03, with the labels that each got.

#28 21 űrhajó mozgása
  __pycache__/asteroid.cpython-312.pyc
  __pycache__/game.cpython-312.pyc
  __pycache__/player.cpython-312.pyc
  __pycache__/settings.cpython-312.pyc
  game.py
  player.py
  settings.py
Labels: python, enhancement, új commit

#32 31 kezdőképernyő
  __pycache__/asteroid.cpython-312.pyc
  __pycache__/game.cpython-312.pyc
  __pycache__/player.cpython-312.pyc
  __pycache__/settings.cpython-312.pyc
  game.py
Labels: python

#39 29 vltoztatsok s lvedk elksztse
  .gitignore
  Képek/blast.png
  Képek/pixil-frame-1.png
  Képek/player_stand.png
  Képek/űrhajó.gif
  Képek/űrhajó_sheet.png
  game.py
  player.py
  settings.py
Labels: python, enhancement, új commit, pixelart

#45 42 a falról való lepattanás és fix max sebesség
  README.md
  game.py
  player.py
  settings.py
Labels: enhancement

#51 Konfigurálás a settingsben
  game.py
  settings.py
Labels: python, fixing

#54 53 asteroid spawn, de túl nagy a hitbox
  asteroid.py
  game.py
Labels: python, új commit, wontfix

#60 53 asteroid spawn
  asteroid.py
Labels: help, python

#61 56 font tpus importlsa s settings finomtgats
  Képek/player-0.png
  Képek/player-1.png
  Képek/player-2.png
  Képek/player-3.png
  Képek/player-4.png
  Képek/player_stand.png
  Romulus.ttf
  ido.py
  menuk.py
  player.py
  settings.py
  windows_command_prompt.zip
Labels: enhancement, új commit, question

#64 53 asteroid spawn
  asteroid.py
  game.py
  player.py
Labels: help, python

#65 spawn done, but it should be fixed ASAP
  game.py
Labels: help, python

#68 62 lövedék létrehozása
  Képek/blast-0.png
  Képek/blast-1.png
  Képek/blast.png
  Képek/player-0.png
  Képek/player-1.png
  Képek/player-2.png
  Képek/player-3.png
  Képek/player-4.png
  Képek/player_stand.png
  bullets.py
  game.py
  game2.py
  game3.py
  ido.py
  menuk.py
  player.py
  settings.py
Labels: python, enhancement, pixelart, fixing
