Repository szollingerrajmund/SpaceHunter, pull requests merged in 2024-02, with the labels that each got.

#17 github probléma megoldása
  Képek/Asteroid 100x100.png
  Képek/Asteroid 1600x1600.png
  Képek/asteroid animation.gif
  Képek/asteroid bottom-frame animation.gif
  Képek/asteroid bottom-frame.png
  Képek/asteroid upper-frame animation.gif
  Képek/asteroid upper-frame.png
  Képek/background.png
  Képek/ellenség_hajója.gif
  Képek/flamin-asteroid animation.gif
  Képek/kész_hajó.gif
  Képek/kész_űrhajó_sheet.png
  Képek/pixil-gif-drawing.gif
  Képek/player-0.png
  Képek/player-1.png
  Képek/player-2.png
  Képek/player-3.png
  Képek/player-4.png
  game.py
  main.py
  player.py
Labels: enhancement

#19 most már jó
  Képek/asteroid animation.gif
  Képek/asteroid bottom-frame animation.gif
  Képek/asteroid bottom-frame.png
  Képek/asteroid upper-frame animation.gif
  Képek/asteroid upper-frame.png
  Képek/background.png
  Képek/flamin-asteroid animation.gif
  Képek/kész_hajó.gif
  Képek/kész_űrhajó_sheet.png
  Képek/pixil-gif-drawing.gif
  __pycache__/game.cpython-312.pyc
  __pycache__/settings.cpython-312.pyc
Labels: képek

#24 probléma megoldása
  Képek/asteroid/1.png
  Képek/asteroid/10.png
  Képek/asteroid/2.png
  Képek/asteroid/3.png
  Képek/asteroid/4.png
  Képek/asteroid/5.png
  Képek/asteroid/6.png
  Képek/asteroid/7.png
  Képek/asteroid/8.png
  Képek/asteroid/9.png
  asteroid.py
  game.py
Labels: python
