Repository szollingerrajmund/SpaceHunter, pull requests merged in 2024-04, with the labels that each got.

#76 times up
  game.py
Labels: fixing

#78 77 asteroid spawn javítás
  .gitignore
  asteroid.py
  game.py
  main.py
Labels: python

#79 75 lövedék és asteroidák ütközések coallison igazítása ütközéskor robbanás
  .gitignore
  asteroid.py
  bullets.py
  game.py
  main.py
  player.py
  sound.py
Labels: fixing

#82 kész az ütközés
  game.py
  ido.py
  player.py
Labels: enhancement

#85 pontrendszer kb kész
  README.md
  game.py
  menuk.py
  moduls.py
  sound.py
Labels: enhancement

#88 87 utols bug fixlsok
  asteroids.py
  bullet.py
  games.py
  main.py
  menu1.py
  menus.py
  moduls.py
  music.py
  player.py
Labels: python

#89 bugok fixálása
  bullets.py
  game.py
  main.py
Labels: python

#90 végső commit
  asteroids.py
  game.py
  menus.py
  moduls.py
Labels: új commit, fixing

#92 kész a ppt ._.
  PPT/Játék/Hajó_kezdőképernyő.PNG
  PPT/Játék/Játék.PNG
  PPT/Játék/Játék_vége_menu.PNG
  PPT/Játék/Játékvége.PNG
  PPT/Játék/help_menu.PNG
  PPT/Játék/rakétás_fehér_háttét.png
  PPT/Játék/rakétás_háttér.png
  PPT/Játék/Áttűnő képernyő.PNG
  PPT/Kód/Bullets.PNG
  PPT/Kód/Főmenu.PNG
  PPT/Kód/Game_menük_kep.PNG
  PPT/Kód/Keys_input.PNG
  PPT/Kód/játék_vége_menu_2.PNG
  PPT/Kód/player.PNG
  PPT/Kód/player1.PNG
  PPT/Kód/sound.PNG
  PPT/Kód/start_menu.PNG
  PPT/Kód/start_menu_áttünés.PNG
  PPT/Space Hunter.pptx
Labels: képek, Sűrgős

#94 93 bug fixing
  Képek/mark.jpg
  game.py
Labels: Sűrgős, fixing
